// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

// Defines values for WorkspaceState.
const (
	WorkspaceStateError   WorkspaceState = "error"
	WorkspaceStateRunning WorkspaceState = "running"
	WorkspaceStateStopped WorkspaceState = "stopped"
	WorkspaceStateUnknown WorkspaceState = "unknown"
)

// Valid indicates whether the value is a known member of the WorkspaceState enum.
func (e WorkspaceState) Valid() bool {
	switch e {
	case WorkspaceStateError:
		return true
	case WorkspaceStateRunning:
		return true
	case WorkspaceStateStopped:
		return true
	case WorkspaceStateUnknown:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Info defines model for Info.
type Info struct {
	Agents   []string `json:"agents"`
	Runtimes []string `json:"runtimes"`
	Version  string   `json:"version"`
}

// SecretInfo defines model for SecretInfo.
type SecretInfo struct {
	Description    *string   `json:"description,omitempty"`
	Envs           *[]string `json:"envs,omitempty"`
	Header         *string   `json:"header,omitempty"`
	HeaderTemplate *string   `json:"headerTemplate,omitempty"`
	Hosts          *[]string `json:"hosts,omitempty"`
	Name           string    `json:"name"`
	Path           *string   `json:"path,omitempty"`
	Type           string    `json:"type"`
}

// SecretName defines model for SecretName.
type SecretName struct {
	Name string `json:"name"`
}

// SecretService defines model for SecretService.
type SecretService struct {
	Description    *string   `json:"description,omitempty"`
	EnvVars        *[]string `json:"envVars,omitempty"`
	HeaderName     string    `json:"headerName"`
	HeaderTemplate *string   `json:"headerTemplate,omitempty"`
	HostPattern    string    `json:"hostPattern"`
	Name           string    `json:"name"`
}

// SecretServicesList defines model for SecretServicesList.
type SecretServicesList struct {
	Items []SecretService `json:"items"`
}

// SecretsList defines model for SecretsList.
type SecretsList struct {
	Items []SecretInfo `json:"items"`
}

// Workspace defines model for Workspace.
type Workspace struct {
	Agent      string              `json:"agent"`
	Id         string              `json:"id"`
	Model      *string             `json:"model,omitempty"`
	Name       string              `json:"name"`
	Paths      WorkspacePaths      `json:"paths"`
	Project    string              `json:"project"`
	State      WorkspaceState      `json:"state"`
	Timestamps WorkspaceTimestamps `json:"timestamps"`
}

// WorkspaceId defines model for WorkspaceId.
type WorkspaceId struct {
	Id string `json:"id"`
}

// WorkspacePaths defines model for WorkspacePaths.
type WorkspacePaths struct {
	Configuration string `json:"configuration"`
	Source        string `json:"source"`
}

// WorkspaceState defines model for WorkspaceState.
type WorkspaceState string

// WorkspaceTimestamps defines model for WorkspaceTimestamps.
type WorkspaceTimestamps struct {
	Created int64  `json:"created"`
	Started *int64 `json:"started,omitempty"`
}

// WorkspacesList defines model for WorkspacesList.
type WorkspacesList struct {
	Items []Workspace `json:"items"`
}
