// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

// Agent defines model for Agent.
type Agent struct {
	Name *string `json:"name,omitempty"`
}

// AgentsList defines model for AgentsList.
type AgentsList struct {
	Items *[]Agent `json:"items,omitempty"`
}
