// Package workspace provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package workspace

// WorkspaceConfiguration defines model for WorkspaceConfiguration.
type WorkspaceConfiguration struct {
	Name *string `json:"name,omitempty"`
}
