// Package workspace provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package workspace

// EnvironmentVariable defines model for EnvironmentVariable.
type EnvironmentVariable struct {
	// Name Name of the environment variable
	Name string `json:"name"`

	// Secret Name of the secret containing the value (mutually exclusive with value)
	Secret *string `json:"secret,omitempty"`

	// Value Value of the environment variable (mutually exclusive with secret)
	Value *string `json:"value,omitempty"`
}

// McpCommand defines model for McpCommand.
type McpCommand struct {
	// Args Arguments to pass to the command
	Args *[]string `json:"args,omitempty"`

	// Command Command to run to start the MCP server
	Command string `json:"command"`

	// Env Environment variables to set for the command
	Env *map[string]string `json:"env,omitempty"`

	// Name Name of the MCP server
	Name string `json:"name"`
}

// McpConfiguration defines model for McpConfiguration.
type McpConfiguration struct {
	// Commands List of command-based MCP servers
	Commands *[]McpCommand `json:"commands,omitempty"`

	// Servers List of URL-based MCP servers
	Servers *[]McpServer `json:"servers,omitempty"`
}

// McpServer defines model for McpServer.
type McpServer struct {
	// Headers HTTP headers to send with requests to the MCP server
	Headers *map[string]string `json:"headers,omitempty"`

	// Name Name of the MCP server
	Name string `json:"name"`

	// Url URL of the MCP server
	Url string `json:"url"`
}

// Mount defines model for Mount.
type Mount struct {
	// Host Path in the host filesystem. Can use $SOURCES or $HOME variables (e.g., "$SOURCES/../main", "$HOME/.gitconfig", "/absolute/path")
	Host string `json:"host"`

	// Ro Mount as read-only. Defaults to false (read-write).
	Ro *bool `json:"ro,omitempty"`

	// Target Path in the workspace filesystem where the host path will be mounted. Can use $SOURCES or $HOME variables.
	Target string `json:"target"`
}

// WorkspaceConfiguration defines model for WorkspaceConfiguration.
type WorkspaceConfiguration struct {
	Environment *[]EnvironmentVariable `json:"environment,omitempty"`
	Mcp         *McpConfiguration      `json:"mcp,omitempty"`

	// Mounts List of directories to mount in the workspace. Supports $SOURCES (workspace sources directory) and $HOME (user home directory) variables.
	Mounts *[]Mount `json:"mounts,omitempty"`

	// Skills List of folders containing skills (SKILL.md and related files) to be provided to the agent.
	Skills *[]string `json:"skills,omitempty"`
}
