// Package workspace provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package workspace

// Defines values for NetworkConfigurationMode.
const (
	Allow NetworkConfigurationMode = "allow"
	Deny  NetworkConfigurationMode = "deny"
)

// Valid indicates whether the value is a known member of the NetworkConfigurationMode enum.
func (e NetworkConfigurationMode) Valid() bool {
	switch e {
	case Allow:
		return true
	case Deny:
		return true
	default:
		return false
	}
}

// EnvironmentVariable defines model for EnvironmentVariable.
type EnvironmentVariable struct {
	// Name Name of the environment variable
	Name string `json:"name"`

	// Secret Name of the secret containing the value (mutually exclusive with value)
	Secret *string `json:"secret,omitempty"`

	// Value Value of the environment variable (mutually exclusive with secret)
	Value *string `json:"value,omitempty"`
}

// McpCommand defines model for McpCommand.
type McpCommand struct {
	// Args Arguments to pass to the command
	Args *[]string `json:"args,omitempty"`

	// Command Command to run to start the MCP server
	Command string `json:"command"`

	// Env Environment variables to set for the command
	Env *map[string]string `json:"env,omitempty"`

	// Name Name of the MCP server
	Name string `json:"name"`
}

// McpConfiguration defines model for McpConfiguration.
type McpConfiguration struct {
	// Commands List of command-based MCP servers
	Commands *[]McpCommand `json:"commands,omitempty"`

	// Servers List of URL-based MCP servers
	Servers *[]McpServer `json:"servers,omitempty"`
}

// McpServer defines model for McpServer.
type McpServer struct {
	// Headers HTTP headers to send with requests to the MCP server
	Headers *map[string]string `json:"headers,omitempty"`

	// Name Name of the MCP server
	Name string `json:"name"`

	// Url URL of the MCP server
	Url string `json:"url"`
}

// Mount defines model for Mount.
type Mount struct {
	// Host Path in the host filesystem. Can use $SOURCES or $HOME variables (e.g., "$SOURCES/../main", "$HOME/.gitconfig", "/absolute/path")
	Host string `json:"host"`

	// Ro Mount as read-only. Defaults to false (read-write).
	Ro *bool `json:"ro,omitempty"`

	// Target Path in the workspace filesystem where the host path will be mounted. Can use $SOURCES or $HOME variables.
	Target string `json:"target"`
}

// NetworkConfiguration defines model for NetworkConfiguration.
type NetworkConfiguration struct {
	// Hosts List of hostnames to allow in deny mode.
	Hosts *[]string `json:"hosts,omitempty"`

	// Mode Network access mode. 'allow' permits all. 'deny' blocks everything except the specified hosts/CIDRs. Defaults to 'deny'.
	Mode *NetworkConfigurationMode `json:"mode,omitempty"`
}

// NetworkConfigurationMode Network access mode. 'allow' permits all. 'deny' blocks everything except the specified hosts/CIDRs. Defaults to 'deny'.
type NetworkConfigurationMode string

// WorkspaceConfiguration defines model for WorkspaceConfiguration.
type WorkspaceConfiguration struct {
	Environment *[]EnvironmentVariable `json:"environment,omitempty"`

	// Features Features to add to the workspace, compatible with devcontainers features (https://containers.dev/implementors/features/). Keys are feature identifiers (e.g. OCI image references), values are feature-specific options.
	Features *map[string]map[string]interface{} `json:"features,omitempty"`
	Mcp      *McpConfiguration                  `json:"mcp,omitempty"`

	// Mounts List of directories to mount in the workspace. Supports $SOURCES (workspace sources directory) and $HOME (user home directory) variables.
	Mounts  *[]Mount              `json:"mounts,omitempty"`
	Network *NetworkConfiguration `json:"network,omitempty"`

	// Secrets List of secret names to inject into the workspace.
	Secrets *[]string `json:"secrets,omitempty"`

	// Skills List of folders containing skills (SKILL.md and related files) to be provided to the agent.
	Skills *[]string `json:"skills,omitempty"`
}
