openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /list:
    get:
      summary: List the Workspaces
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkspacesList'
              example:
                items:
                  - id: d07830f8ce31df3dc3bbcbbb4cd94470338bd26b45a5def8fe59b3198223ff18
                    name: workspace1
                    paths:
                      source: /home/user/workspace1
                      configuration: /home/user/workspace1/.kortex
                  - id: 20cb499a4561703e973631fa3036cc8be9a06b709759d23a7d7f6dd1df146d95
                    name: workspace2
                    paths:
                      source: /home/user/workspace2
                      configuration: /home/user/.kortex-cli/workspaces/workspace2
components:
  schemas:
    WorkspacePaths:
      type: object
      additionalProperties: false
      properties:
        source:
          type: string
        configuration:
          type: string
      required:
      - source
      - configuration
    Workspace:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        name:
          type: string
        paths:
          $ref: '#/components/schemas/WorkspacePaths'
      required:
      - id
      - name
      - paths
    WorkspacesList:
      type: object
      additionalProperties: false
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Workspace'
      required:
      - items
